#!/usr/bin/env bash
# Function to print domain information

print_domain_info() {
    local domain="$1"
    local subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 2 ]; then
    print_domain_info "$1" "$2"
else
    print_domain_info "$1" "www"
    print_domain_info "$1" "lb-01"
    print_domain_info "$1" "web-01"
    print_domain_info "$1" "web-02"
fi
