#!/usr/bin/env bash
# Function to print domain information

domain_info() {
    local domain="$1"
    local subdomain="$2"
     line=$(dig "$subdomain"."$domain" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
    echo "$subdomain $line" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
}

if [ "$#" -eq 1 ]; then
    print_domain_info "$1" "www"
    print_domain_info "$1" "lb-01"
    print_domain_info "$1" "web-01"
    print_domain_info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi
