#!/usr/bin/env bash

# Check parameters for transferring the files
if [ $# -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME"
    exit 1
fi

# Assigning variables to the four parameters
file_path=$1
ip_address=$2
username=$3
path_to_ssh_key=$4

# Disabling the strict host key checking
scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$file_path" "$username@"$ip_address":~/

# Confirming if the transfer is successful
if [ $? -eq 0 ]; then
    echo "File transfer was successful"
else
    echo "File transfer failed"
fi
