#!/usr/bin/env bash

# commands for installing nginx

sudo apt-get update
sudo apt-get install -y nginx  # Added -y option to apt-get for non-interactive installation
sudo ufw allow 'Nginx HTTP'    # Corrected syntax for ufw rule
sudo nginx -t
sudo service nginx reload
sudo service nginx restart
echo "Hello world!" | sudo tee /var/www/html/index.html
