#!/usr/bin/env bash
# commands for installing nginx

sudo apt-get -y update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'
sudo nginx -t
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart

