#!/usr/bin/env bash
# commands for installing nginx

sudo apt-get -y updatei
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx reload
