#!/usr/bin/env bash
# Creating a script to install and configure HAProxy on lb-01 server
# Configuring HAProxy to send traffic to web-01 and web-02 servers
# Distributing requests using a roundrobin algorithm
# Making sure that HAProxy can be managed via an init script
# Installing and configuring HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# editing the configuration file
server_config=\
"
frontend  andy-frontend
        bind *:80
        mode http
        default_backend andy-backend
backend andy-backend
        balance roundrobin
        server 510198-web-01 54.157.180.70:80 check
        server 510198-web-02 54.173.15.54:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enabling haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
