#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

echo "server { listen 80; }" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Create a symbolic link to enable the default site
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
