#!/usr/bin/env bash
# Display a list of currently running processes with user-oriented format and hierarchy
# Display header
# Use ps to display processes with user-oriented format and hierarchy

ps -a -x -u -f
