#!/bin/bash
# Init script to manage manage_my_process

PID_FILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

case "$1" in
    start)
        if [ -f "$PID_FILE" ]; then
            echo "manage_my_process is already started."
        else
            $SCRIPT &
            echo $! > "$PID_FILE"
            echo "manage_my_process started"
        fi
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            kill "$(cat "$PID_FILE")"
            rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running."
        fi
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
