#!/usr/bin/env bash

case "$1" in
  start)
      nohup bash manage_my_process &
      pid=$!
      echo $pid > /var/run/my_process.pid
      echo "manage_my_process started"
      ;;
  stop)
      kill $(cat /var/run/my_process.pid)
      rm /var/run/my_process.pid
      echo "manage_my_process stopped"
      ;;
  restart)
      kill $(cat /var/run/my_process.pid)
      rm /var/run/my_process.pid
      nohup bash manage_my_process &
      pid=$!
      echo $pid > /var/run/my_process.pid
      echo "manage_my_process restarted"
      ;;
  *)
      echo "Usage: manage_my_process {start|stop|restart}"
      ;;
esac
