#!/usr/bin/env bash
# Display lines containing the word 'bash' and get the PID
# shellcheck disable=SC2009
# Display lines containing 'bash' and extract the PID

./1-list_your_processes | grep "bash"
