#!/usr/bin/env bash
# This script is stopping the 4-to_infinity_and_beyond process

# Get the PID of the 4-to_infinity_and_beyond process
pid=$(ps aux | grep 4-to_infinity_and_beyond | grep -v grep | awk '{print $2}')

# Terminate the process
kill -9 $pid
