#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process without using kill or killall
# Find the process ID (PID) of 4-to_infinity_and_beyond

pid=$(ps aux | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

# Terminate the process by sending a SIGTERM signal
kill -15 "$pid"
