#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely with a sleep of 2 seconds between iterations
# Print "I am invincible!!!" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "To infinity and beyond"
    sleep 2
done
