#!/usr/bin/env bash
# This script is displaying the content of the /etc/passwd file

while IFS=: read -r username userid otherinfo homedir
do
 echo "$username:$userid:$homedir" | cut -f 1,3,6 -d ':'
done < /etc/passwd
