#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but for the 4th iteration, it displays "Bad luck", and for the 8th iteration, it displays "Good luck"

counter=1
while [ $counter -le 10 ]
do
 if [ $counter -eq 4 ]; then
  echo "Bad luck"
 elif [ $counter -eq 8 ]; then
  echo "Good luck"
 else
  echo "Best School"
 fi
 ((counter++))
done
