#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but for the 4th iteration, it displays "Bad luck", and for the 8th iteration, it displays "Good luck"

count=1

while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((count++))
done
