#!/usr/bin/env bash
# This script is displaying the content of the current directory in a list format, where only the part of the name after the first dash is displayed

for file in $(ls -p | grep -v /)
do
 echo $file | cut -d'-' -f2-
done
