#!/usr/bin/env bash
# Setting up a strict firewall 
# It disallows incomming connection and allow outgoing connection

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
