#!/usr/bin/env bash
# This script modifies the /etc/hosts file by creating a new version in the home directory.

# Copy the existing /etc/hosts file to the home directory with the name 'hosts.new'.
cp /etc/hosts ~/hosts.new

# Add a line to the 'hosts.new' file, mapping 127.0.0.2 to 'localhost'.
echo "127.0.0.2		localhost" > ~/hosts.new

# Append another line to the 'hosts.new' file, mapping 8.8.8.8 to 'facebook.com'.
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Overwrite the original /etc/hosts file with the modified 'hosts.new' file.
cp -f ~/hosts.new /etc/hosts
