#!/usr/bin/env bash
Configuration for the server block
server {
    # Listen on port 80
    listen 80;
    listen [::]:80 default_server;

    # Add header with server hostname
    add_header X-Served-By $hostname;

    # Set root directory for HTML files
    root   /etc/nginx/html;

    # Define index files
    index  index.html index.htm;

    # Redirect /redirect_me to YouTube
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Set root directory for /airbnb-onepage
    root /var/www/html;

    # Define server name
    server_name _;

    # Proxy requests to /airbnb-onepage
    location /airbnb-onepage {
        proxy_pass http://0.0.0.0:5000/airbnb-onepage;
    }

    # Serve static files from /data/web_static/current/
    location /hbnb_static {
        alias /data/web_static/current/;
    }

    # Default location block
    location / {
        # Try to serve request as file, then directory, else 404
        try_files $uri $uri/ =404;
    }
}
