#!/usr/bin/env bash
# Configuration for the server block
server {
    # Listen on port 80 as default server
    listen 80 default_server;
    listen [::]:80 default_server;

    # Set root directory for HTML files
    root /var/www/html;

    # Define index files
    index index.html index.htm index.nginx-debian.html;

    # Define server name
    server_name_;

    # Add header with server hostname
    add_header X-Served-By $hostname;

    # Serve static files from /home/ubuntu/AirBnB_clone_v4/web_dynamic/static/
    location /static/ {
        alias /home/ubuntu/AirBnB_clone_v4/web_dynamic/static/;
        try_files $uri $uri/ =404;
    }

    # Default location block
    location / {
        # Try to serve request as file, then directory, else 404
        try_files $uri $uri/ =404;
    }

    # Proxy requests to /airbnb-onepage
    location /airbnb-onepage {
        proxy_pass http://0.0.0.0:5000/airbnb-onepage;
    }

    # Proxy requests to /airbnb-dynamic/number_odd_or_even/<number>
    location ~ ^/airbnb-dynamic/number_odd_or_even/([0-9]+)$ {
        proxy_pass http://0.0.0.0:5001/number_odd_or_even/$1;
    }

    # Proxy requests to /api/
    location /api/ {
        proxy_pass http://0.0.0.0:5002;
    }

    # Rewrite request to redirect to https://th3-gr00t.tk/
    if ($request_filename ~ redirect_me) {
        rewrite ^ https://th3-gr00t.tk/ permanent;
    }

    # Serve custom 404 error page
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }

    # Serve static files from /data/web_static/current/
    location /hbnb_static {
        alias /data/web_static/current/;
    }
}
